In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re

from konlpy.tag import Okt

In [2]:
df1 = pd.read_csv('data/고민상담.csv', encoding ='utf-8')
df2 = pd.read_csv('data/공황장애고민.csv', encoding ='utf-8')
df3 = pd.read_csv('data/군입대고민.csv', encoding ='utf-8')
df4 = pd.read_csv('data/다이어트고민.csv', encoding ='utf-8')
df5 = pd.read_csv('data/대학생활고민.csv', encoding ='utf-8')
df6 = pd.read_csv('data/몸매고민.csv', encoding ='utf-8')
df7 = pd.read_csv('data/부부고민.csv', encoding ='utf-8')
df8 = pd.read_csv('data/불안장애고민.csv', encoding ='utf-8')
df9 = pd.read_csv('data/사랑고민.csv', encoding ='utf-8')
df10 = pd.read_csv('data/심리상담.csv', encoding ='utf-8')
df11 = pd.read_csv('data/연상고민.csv', encoding ='utf-8')
df12 = pd.read_csv('data/연애고민.csv', encoding ='utf-8')
df13 = pd.read_csv('data/연인관계고민.csv', encoding ='utf-8')
df14 = pd.read_csv('data/연하고민.csv', encoding ='utf-8')
df15 = pd.read_csv('data/외모고민.csv', encoding ='utf-8')
df16 = pd.read_csv('data/우울증고민.csv', encoding ='utf-8')
df17 = pd.read_csv('data/이별고민.csv', encoding ='utf-8')
df18 = pd.read_csv('data/이혼고민.csv', encoding ='utf-8')
df19 = pd.read_csv('data/입시고민.csv', encoding ='utf-8')
df20 = pd.read_csv('data/직장고민.csv', encoding ='utf-8')
df21 = pd.read_csv('data/직장생활고민.csv', encoding ='utf-8')
df22 = pd.read_csv('data/진로고민.csv', encoding ='utf-8')
df23 = pd.read_csv('data/취업고민.csv', encoding ='utf-8')
df24 = pd.read_csv('data/친구관계고민.csv', encoding ='utf-8')
df25 = pd.read_csv('data/퇴사고민.csv', encoding ='utf-8')
df26 = pd.read_csv('data/피부고민.csv', encoding ='utf-8')
df27 = pd.read_csv('data/학업고민.csv', encoding ='utf-8')

In [6]:
df1

Unnamed: 0  index                                               text
0             0      0                          저 직업고민상담쫌 해주세요ㅜㅜㅜㅜㅜ제발>>>>
1             1      1  실시간으로 고민 상담해주는 사이트좀 알려줘요>>> > >실시간으로 고민 상담해주는 ...
2             2      2  고민상담전화 개인정보>>> >고민상담 전화 하려는데요>친구 관계거든요 애들이랑 싸워...
3             4      4  입시생고민 상담>>> >안녕하세요 고 남학생인데요 이러는 시간이 없는거 알지만 들어...
4             5      5  고민상담은 삼촌>>>            >>>>         >>>>>     ...
..          ...    ...                                                ...
914         995    995  고민상담>>> >>제가요 중학생인데요>>제가 부쩍 중학생이 되니>>노는 얘들이 두렵...
915         996    996  안녕하세요고민상담입니다혹시 생리는 언제하나용저는 이제 학년이 되고 가슴이 나오는것은...
916         997    997  고학생 유학고민상담좀 해주세요ㅠㅠ >지금고이고 일반고 재학중이에요 성적은 등급정도 ...
917         998    998  고민상담알바ㅜ 내공드릴게요>>> >고민상담전화같은알바어떻게하나요>제가누구고민들어주고...
918         999    999  연애 고민 상담 부탁드립니다 >>> >안녕하세요 저는 살 여자 입니다 >현재 신발 ...

[919 rows x 3 columns]

In [3]:
def test(s):
    hangul = re.compile('[^ ㄱ-ㅣ가-힣]+') # 한글과 띄어쓰기를 제외한 모든 글자
    result = hangul.sub('', s) # 한글과 띄어쓰기를 제외한 모든 부분을 제거
    return result

In [7]:
def make_label(df):
    df= df.drop(['Unnamed: 0','index'], axis =1)
    df.columns = ['text']
    df['label'] = 0
    for i in range(len(df['text'])):
        if df['text'][i] == '\n':
            df['label'][i-1] = 1
            df = df.drop([i])
            
    df['text'] = df['text'].apply(lambda x : test(x))

    return df

In [8]:
df1 = make_label(df1)
df2 = make_label(df2)
df3 = make_label(df3)
df4 = make_label(df4)
df5 = make_label(df5)
df6 = make_label(df6)
df7 = make_label(df7)
df8 = make_label(df8)
df9 = make_label(df9)
df10 = make_label(df10)
df11 = make_label(df11)
df12 = make_label(df12)
df13 = make_label(df13)
df14 = make_label(df14)
df15 = make_label(df15)
df16 = make_label(df16)
df17 = make_label(df17)
df18 = make_label(df18)
df19 = make_label(df19)
df20 = make_label(df20)
df21 = make_label(df21)
df22 = make_label(df22)
df23 = make_label(df23)
df24 = make_label(df24)
df25 = make_label(df25)
df26 = make_label(df26)
df27 = make_label(df27)


In [10]:
df1.label = 1
df2.label = 2
df3.label = 3
df4.label = 4
df5.label = 5
df6.label = 6
df7.label = 7
df8.label = 8
df9.label = 9
df10.label = 10
df11.label = 11
df12.label = 12
df13.label = 13
df14.label = 14
df15.label = 15
df16.label = 16
df17.label = 17
df18.label = 18
df19.label = 19
df20.label = 20
df21.label = 21
df22.label = 22
df23.label = 23
df24.label = 24
df25.label = 25
df26.label = 26
df27.label = 27

In [12]:
f_df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,\
          df21,df22,df23,df24,df25,df26,df27], axis=0)

In [14]:
f_df.index = list(range(len(f_df)))

In [18]:
from tqdm import tqdm_notebook
from konlpy.tag import Okt

RE_FILTER = re.compile("[.,!?\"':;~()]")

def pos_tag(sentences):
    from tqdm import tqdm_notebook
    # KoNLPy 형태소분석기 설정
    tagger = Okt()
    
    # 문장 품사 변수 초기화
    sentences_pos = []
    
    # 모든 문장 반복
    for sentence in tqdm_notebook(sentences):
        # 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        
        # 배열인 형태소분석의 출력을 띄어쓰기로 구분하여 붙임
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
        
    return sentences_pos

In [21]:
data= pos_tag(f_df.text)

In [25]:
df = pd.DataFrame(data)
df.columns= ['text']
df['label']= f_df.label

In [27]:
df.to_csv('고민분류용df.csv', encoding= 'utf-8')

In [34]:
data = []
df.text.apply(lambda x: data.append(x))

0        None
1        None
2        None
3        None
4        None
         ... 
24637    None
24638    None
24639    None
24640    None
24641    None
Name: text, Length: 24642, dtype: object

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf = TfidfVectorizer(max_features= 3000)

In [40]:
tfidf.fit(data)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=3000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [48]:
data = tfidf.transform(data).toarray()

In [50]:
data.shape

(24642, 3000)

In [133]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, df['label'], test_size = 0.2, random_state = 77)

In [134]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [135]:
x_train.shape

(19713, 3000)

In [136]:
y_train.shape

(19713, 28)

In [137]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(512, activation ='relu', input_shape=(3000,)))
model.add(layers.Dense(256, activation= 'relu'))
model.add(layers.Dense(256, activation= 'relu'))
model.add(layers.Dense(64, activation= 'relu'))
model.add(layers.Dense(28, activation='softmax'))

In [138]:
model.compile(optimizer='adam',\
              loss='categorical_crossentropy',\
              metrics=['accuracy'])

In [139]:
history = model.fit(x_train, y_train,\
                    epochs=5, batch_size = 128,validation_split=0.2)

Train on 15770 samples, validate on 3943 samples
Epoch 1/5
15770/15770 [==============================] - ETA: 1:04 - loss: 3.3307 - acc: 0.031 - ETA: 23s - loss: 3.3292 - acc: 0.062 - ETA: 15s - loss: 3.3267 - acc: 0.06 - ETA: 12s - loss: 3.3249 - acc: 0.06 - ETA: 11s - loss: 3.3225 - acc: 0.06 - ETA: 10s - loss: 3.3203 - acc: 0.06 - ETA: 9s - loss: 3.3158 - acc: 0.0668 - ETA: 8s - loss: 3.3075 - acc: 0.066 - ETA: 7s - loss: 3.2971 - acc: 0.067 - ETA: 7s - loss: 3.2877 - acc: 0.063 - ETA: 6s - loss: 3.2722 - acc: 0.070 - ETA: 6s - loss: 3.2519 - acc: 0.089 - ETA: 6s - loss: 3.2388 - acc: 0.099 - ETA: 5s - loss: 3.2127 - acc: 0.113 - ETA: 5s - loss: 3.1880 - acc: 0.125 - ETA: 5s - loss: 3.1540 - acc: 0.144 - ETA: 5s - loss: 3.1129 - acc: 0.161 - ETA: 4s - loss: 3.0681 - acc: 0.181 - ETA: 4s - loss: 3.0260 - acc: 0.195 - ETA: 4s - loss: 2.9858 - acc: 0.207 - ETA: 4s - loss: 2.9306 - acc: 0.225 - ETA: 4s - loss: 2.8797 - acc: 0.239 - ETA: 3s - loss: 2.8253 - acc: 0.255 - ETA: 3s - loss: 

In [140]:
model.evaluate(x_test,y_test)

4929/4929 [==============================] - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - 1s 106us/step


[0.63008880165388, 0.847839318320146]

In [145]:
sentence ='와이프가 저 몰래 연애를 합니다 '
test_sen = tfidf.transform([sentence]).toarray()
test_sen

array([[0., 0., 0., ..., 0., 0., 0.]])

In [146]:
model.predict_classes(test_sen)

array([1], dtype=int64)

In [88]:
sentence ='요새 뱃살이 너무나 쪄서 문제에요'

test_sen = tfidf.transform([sentence]).toarray()
model.predict_classes(test_sen)

array([3], dtype=int64)

In [89]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [92]:
x_train.shape

(19713, 3000)

In [97]:
clf.fit(x_train, y_train)

KeyboardInterrupt: 

In [103]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)


In [111]:
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [108]:
y_train= y_train.values

In [110]:
y_train.shape

(19713,)

In [112]:
y_pred = forest.predict(x_test)

In [114]:
from sklearn import metrics 

In [115]:
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

정확도 : 0.8920673564617569


In [130]:
sentence ='요새 취업걱정 때문에 고민이에요'

test_sen = tfidf.transform([sentence]).toarray()

In [131]:
forest.predict(test_sen)

array([21], dtype=int64)